
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20160615 (GIT 4ac7450)
//----------------------------------------------------

package ensamblador;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int HALT = 59;
  public static final int AF = 76;
  public static final int EXX = 66;
  public static final int SP = 77;
  public static final int SL = 24;
  public static final int OTIR = 85;
  public static final int SCF = 57;
  public static final int FX = 67;
  public static final int INIR = 80;
  public static final int LDI = 68;
  public static final int LDD = 70;
  public static final int POP = 102;
  public static final int SUB = 35;
  public static final int RR = 95;
  public static final int OUT = 83;
  public static final int RL = 93;
  public static final int LD = 12;
  public static final int NOP = 58;
  public static final int DEC = 42;
  public static final int SBC = 36;
  public static final int EX = 65;
  public static final int RRCA = 90;
  public static final int OUTI = 84;
  public static final int LDDR = 71;
  public static final int OUTD = 86;
  public static final int EI = 61;
  public static final int COMA = 6;
  public static final int LPAR = 4;
  public static final int RST = 52;
  public static final int CPL = 54;
  public static final int CPI = 72;
  public static final int Z = 26;
  public static final int RLCA = 88;
  public static final int CPD = 74;
  public static final int JR = 10;
  public static final int ADD = 33;
  public static final int ADC = 34;
  public static final int R = 19;
  public static final int JP = 9;
  public static final int PUSH = 101;
  public static final int LDIR = 69;
  public static final int DJ = 11;
  public static final int P = 31;
  public static final int DI = 60;
  public static final int N = 2;
  public static final int MAS = 7;
  public static final int M = 32;
  public static final int DE = 17;
  public static final int PO = 29;
  public static final int DOS = 8;
  public static final int I = 18;
  public static final int BIT = 43;
  public static final int PH = 47;
  public static final int EOF = 0;
  public static final int C = 28;
  public static final int CCF = 56;
  public static final int RPAR = 5;
  public static final int B = 46;
  public static final int PE = 30;
  public static final int A = 20;
  public static final int INI = 79;
  public static final int COM = 22;
  public static final int SRL = 98;
  public static final int IY = 15;
  public static final int IND = 81;
  public static final int IX = 14;
  public static final int INC = 41;
  public static final int CP = 40;
  public static final int SLA = 96;
  public static final int RLD = 99;
  public static final int RLC = 92;
  public static final int SRA = 97;
  public static final int IN = 78;
  public static final int RLA = 89;
  public static final int OR = 38;
  public static final int SET = 44;
  public static final int error = 1;
  public static final int RRD = 100;
  public static final int RRC = 94;
  public static final int RRA = 91;
  public static final int CPDR = 75;
  public static final int RET = 49;
  public static final int RES = 45;
  public static final int ETI = 23;
  public static final int ORG = 103;
  public static final int REG = 21;
  public static final int NZ = 25;
  public static final int HL = 13;
  public static final int NN = 3;
  public static final int BC = 16;
  public static final int RETN = 51;
  public static final int AND = 37;
  public static final int IM2 = 64;
  public static final int IM1 = 63;
  public static final int IM0 = 62;
  public static final int OTDR = 87;
  public static final int CPIR = 73;
  public static final int RETI = 50;
  public static final int DAA = 53;
  public static final int NEG = 55;
  public static final int CALL = 48;
  public static final int XOR = 39;
  public static final int NC = 27;
  public static final int INDR = 82;
  public static final String[] terminalNames = new String[] {
  "EOF",
  "error",
  "N",
  "NN",
  "LPAR",
  "RPAR",
  "COMA",
  "MAS",
  "DOS",
  "JP",
  "JR",
  "DJ",
  "LD",
  "HL",
  "IX",
  "IY",
  "BC",
  "DE",
  "I",
  "R",
  "A",
  "REG",
  "COM",
  "ETI",
  "SL",
  "NZ",
  "Z",
  "NC",
  "C",
  "PO",
  "PE",
  "P",
  "M",
  "ADD",
  "ADC",
  "SUB",
  "SBC",
  "AND",
  "OR",
  "XOR",
  "CP",
  "INC",
  "DEC",
  "BIT",
  "SET",
  "RES",
  "B",
  "PH",
  "CALL",
  "RET",
  "RETI",
  "RETN",
  "RST",
  "DAA",
  "CPL",
  "NEG",
  "CCF",
  "SCF",
  "NOP",
  "HALT",
  "DI",
  "EI",
  "IM0",
  "IM1",
  "IM2",
  "EX",
  "EXX",
  "FX",
  "LDI",
  "LDIR",
  "LDD",
  "LDDR",
  "CPI",
  "CPIR",
  "CPD",
  "CPDR",
  "AF",
  "SP",
  "IN",
  "INI",
  "INIR",
  "IND",
  "INDR",
  "OUT",
  "OUTI",
  "OTIR",
  "OUTD",
  "OTDR",
  "RLCA",
  "RLA",
  "RRCA",
  "RRA",
  "RLC",
  "RL",
  "RRC",
  "RR",
  "SLA",
  "SRA",
  "SRL",
  "RLD",
  "RRD",
  "PUSH",
  "POP",
  "ORG"
  };
}

