
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20160615 (GIT 4ac7450)
//----------------------------------------------------

package input;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int L = 6;
  public static final int error = 1;
  public static final int H = 5;
  public static final int file = 3;
  public static final int z80 = 2;
  public static final int nombre = 4;
  public static final int EOF = 0;
  public static final String[] terminalNames = new String[] {
  "EOF",
  "error",
  "z80",
  "file",
  "nombre",
  "H",
  "L"
  };
}

